# Generated by Django 2.2.1 on 2019-09-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='StockDB',
        ),
    ]
